Public Class TestError
    Inherits System.Web.UI.Page

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Dim arg As String = CType(sender, Button).CommandArgument
        Select Case (arg)
            Case "1"
                ' Exception handled on the Generic Error Page
                Throw New InvalidOperationException("Button 1 was clicked")
            Case "2"
                ' Exception handled on the current page
                Throw New ArgumentOutOfRangeException("Button 2 was clicked")
                'Exit Select
            Case "3"
                ' Exception handled by Application_Error
                Throw New Exception("Button 3 was clicked")
                'Exit Select
            Case "4"
                ' Exception handled on the Http 404 Error Page
                Response.Redirect("NonexistentPage.aspx", False)
                'Exit Select
            Case "5"
                ' Exception handled on the Http Error Page
                Response.Redirect("NonexistentPage-NoCatch.aspx", False)
                'Exit Select
            Case "6"
                ' Exception handled on the Default Redirect Error Page
                Response.Redirect("NonexistentPage-NoCatch.aspx/xxxxx", False)
                'Exit Select
        End Select
    End Sub

    Private Sub Page_Error(ByVal sender As Object, ByVal e As EventArgs)
        ' Get last error from the server
        Dim exc As Exception = Server.GetLastError

        ' Handle exceptions generated by Button 1
        If TypeOf exc Is InvalidOperationException Then
            ' Pass the error on to the Generic Error page
            Server.Transfer("GenericErrorPage.aspx", True)

            ' Handle exceptions generated by Button 2
        ElseIf TypeOf exc Is ArgumentOutOfRangeException Then
            ' Give the user some information, but
            ' stay on the default page
            Response.Write("<h2>Default Page Error</h2>" & vbLf)
            Response.Write(("<p>Provide as much information here as is " _
              & "appropriate to show to the client.</p>" & vbLf))
            Response.Write(("Return to the <a href='../Products/Default.aspx'>" _
              & "Default Page</a>" & vbLf))
            ' Log the exception and notify system operators
            LogManager.LogManagerInstance.LogError("DefaultPage: Unexpected error occured and has been caught in the Application Error event. ", exc)

            ' Clear the error from the server
            Server.ClearError()
        Else
            ' Pass the error on to the default global handler
        End If
    End Sub
End Class