'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Products_Gastro_OtherData_OGD_Diagnoses
    
    '''<summary>
    '''DiagnosesRadNotifier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiagnosesRadNotifier As Global.Telerik.Web.UI.RadNotification
    
    '''<summary>
    '''DiagnosesObjectDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiagnosesObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''RadNotification1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNotification1 As Global.Telerik.Web.UI.RadNotification
    
    '''<summary>
    '''RadFormDecorator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadFormDecorator1 As Global.Telerik.Web.UI.RadFormDecorator
    
    '''<summary>
    '''MainPageRadSplitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainPageRadSplitter As Global.Telerik.Web.UI.RadSplitter
    
    '''<summary>
    '''ControlsRadPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ControlsRadPane As Global.Telerik.Web.UI.RadPane
    
    '''<summary>
    '''PageTitleHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageTitleHeading As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OverallNormalCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OverallNormalCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''RadTabStrip1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTabStrip1 As Global.Telerik.Web.UI.RadTabStrip
    
    '''<summary>
    '''RadMultiPage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultiPage1 As Global.Telerik.Web.UI.RadMultiPage
    
    '''<summary>
    '''RadPageView0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView0 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''divAbnoDiagnosesOeso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAbnoDiagnosesOeso As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''oesodatalist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents oesodatalist As Global.System.Web.UI.WebControls.DataList
    
    '''<summary>
    '''divAbnoDiagnosesStomach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAbnoDiagnosesStomach As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''StomachDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StomachDataList As Global.System.Web.UI.WebControls.DataList
    
    '''<summary>
    '''divAbnoDiagnosesDuodenum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAbnoDiagnosesDuodenum As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DuodenumDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DuodenumDataList As Global.System.Web.UI.WebControls.DataList
    
    '''<summary>
    '''RadPageView3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView3 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''divAbnoDiagnosesCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAbnoDiagnosesCol As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ColonDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ColonDataList As Global.System.Web.UI.WebControls.DataList
    
    '''<summary>
    '''RadPageView5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView5 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''ERCP_DuodenumFieldset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ERCP_DuodenumFieldset As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ERCP_DuodenumTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ERCP_DuodenumTable As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''D50P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D50P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D52P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D52P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D32P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D32P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''RadTabStrip2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTabStrip2 As Global.Telerik.Web.UI.RadTabStrip
    
    '''<summary>
    '''RadMultipageE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultipageE As Global.Telerik.Web.UI.RadMultiPage
    
    '''<summary>
    '''RadPageViewE0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageViewE0 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''divERCPAbnoDiagnosesDuodenum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divERCPAbnoDiagnosesDuodenum As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''D51P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D51P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''divERCPBiliary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divERCPBiliary As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''D138P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D138P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''divERCPAbnoDiagnosesPapillae control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divERCPAbnoDiagnosesPapillae As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''D33P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D33P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D41P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D41P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''PapillaeTumourDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PapillaeTumourDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''D45P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D45P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D65P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D65P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''divERCPAbnoDiagnosesPancreas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divERCPAbnoDiagnosesPancreas As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''D67P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D67P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D66P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D66P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D68P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D68P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D69P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D69P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D74P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D74P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D75P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D75P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''PancreaticOtherTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PancreaticOtherTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RadPageViewE1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageViewE1 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''D140P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D140P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D180P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D180P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D150P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D150P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D145P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D145P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D175P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D175P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D170P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D170P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D195P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D195P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D185P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D185P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D160P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D160P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''divERCPIntrahepatic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divERCPIntrahepatic As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''D198P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D198P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D210P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D210P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D220P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D220P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''BiliaryLeakDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BiliaryLeakDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''BiliaryLeakSiteRadComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BiliaryLeakSiteRadComboBox As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''IntrahepaticTumourDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IntrahepaticTumourDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''D242P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D242P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D243P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D243P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''divERCPExtrahepatic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divERCPExtrahepatic As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''D265P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D265P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D280P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D280P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ExtrahepaticLeakDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtrahepaticLeakDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ExtrahepaticLeakSiteRadComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtrahepaticLeakSiteRadComboBox As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''D290P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D290P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ExtrahepaticTumourDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtrahepaticTumourDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ExtrahepaticTumourRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtrahepaticTumourRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''D325P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D325P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''BeningTR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BeningTR As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''D305P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D305P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D310P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D310P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D315P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D315P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D320P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D320P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D337P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D337P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MalignantTR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MalignantTR As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''D340P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D340P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D345P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D345P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D350P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D350P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D355P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D355P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''D338P2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents D338P2_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''BiliaryOtherTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BiliaryOtherTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''WholeOtherRadComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WholeOtherRadComboBox As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''ButtonsRadPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonsRadPane As Global.Telerik.Web.UI.RadPane
    
    '''<summary>
    '''SaveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveButton As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''CancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButton As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''RadAjaxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As UnisoftERS.ProcedureMaster
        Get
            Return CType(MyBase.Master,UnisoftERS.ProcedureMaster)
        End Get
    End Property
End Class
