'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Products_Gastro_OtherData_OGD_GIBleeds

    '''<summary>
    '''RadStyleSheetManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadStyleSheetManager1 As Global.Telerik.Web.UI.RadStyleSheetManager

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''GIBleedsRadScriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GIBleedsRadScriptManager As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>
    '''GIBleedsRadFormDecorator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GIBleedsRadFormDecorator As Global.Telerik.Web.UI.RadFormDecorator

    '''<summary>
    '''RadNotification1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNotification1 As Global.Telerik.Web.UI.RadNotification

    '''<summary>
    '''MainPageRadSplitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainPageRadSplitter As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''ControlsRadPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ControlsRadPane As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''FormDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GenderField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GenderField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''AgeField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AgeField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''OverallScroreField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OverallScroreField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''rgGIBleeds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgGIBleeds As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''AgeDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AgeDropDownList As Global.Telerik.Web.UI.RadDropDownList

    '''<summary>
    '''AgeScoreLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AgeScoreLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GenderRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GenderRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''SymptomsFieldset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SymptomsFieldset As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MelaenaRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MelaenaRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''MelaenaScoreLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MelaenaScoreLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SyncopeRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SyncopeRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''SyncopeScoreLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SyncopeScoreLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ObservationFieldset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ObservationFieldset As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LowestSystolicBPDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LowestSystolicBPDropDownList As Global.Telerik.Web.UI.RadDropDownList

    '''<summary>
    '''LowestSystolicBPScoreLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LowestSystolicBPScoreLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HighestPulseRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HighestPulseRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''HighestPulseScoreLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HighestPulseScoreLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Fieldset1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fieldset1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UreaDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UreaDropDownList As Global.Telerik.Web.UI.RadDropDownList

    '''<summary>
    '''UreaScoreLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UreaScoreLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HaemoglobinDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HaemoglobinDropDownList As Global.Telerik.Web.UI.RadDropDownList

    '''<summary>
    '''HaemoglobinScoreLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HaemoglobinScoreLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CoMorbiditiesFieldset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CoMorbiditiesFieldset As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HeartFailureRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeartFailureRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''HeartFailureScoreLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeartFailureScoreLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LiverFailureRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiverFailureRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''LiverFailureScoreLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiverFailureScoreLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RenalFailureRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RenalFailureRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RenalFailureScoreLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RenalFailureScoreLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MetastaticCancerRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MetastaticCancerRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''MetastaticCancerScoreLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MetastaticCancerScoreLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EndoscopyFieldset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndoscopyFieldset As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DiagnosisDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiagnosisDropDownList As Global.Telerik.Web.UI.RadDropDownList

    '''<summary>
    '''DiagnosisScoreLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiagnosisScoreLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BleedingDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BleedingDropDownList As Global.Telerik.Web.UI.RadDropDownList

    '''<summary>
    '''BleedingScoreLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BleedingScoreLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RockallProgressBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RockallProgressBar As Global.Telerik.Web.UI.RadProgressBar

    '''<summary>
    '''RebleedProgressBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RebleedProgressBar As Global.Telerik.Web.UI.RadProgressBar

    '''<summary>
    '''BlatchfordProgressBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BlatchfordProgressBar As Global.Telerik.Web.UI.RadProgressBar

    '''<summary>
    '''AdvertEventProgressBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AdvertEventProgressBar As Global.Telerik.Web.UI.RadProgressBar

    '''<summary>
    '''MortalityRadProgressBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MortalityRadProgressBar As Global.Telerik.Web.UI.RadProgressBar

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OverallRiskLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OverallRiskLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SaveRadNotification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveRadNotification As Global.Telerik.Web.UI.RadNotification

    '''<summary>
    '''SaveValidationSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveValidationSummary As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''ButtonsRadPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonsRadPane As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''SaveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''CancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ResetButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResetButton As Global.Telerik.Web.UI.RadButton
End Class
