'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Products_Gastro_OtherData_OGD_QA
    
    '''<summary>
    '''RadNotification1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNotification1 As Global.Telerik.Web.UI.RadNotification
    
    '''<summary>
    '''RadFormDecorator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadFormDecorator1 As Global.Telerik.Web.UI.RadFormDecorator
    
    '''<summary>
    '''MainPageRadSplitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainPageRadSplitter As Global.Telerik.Web.UI.RadSplitter
    
    '''<summary>
    '''ControlsRadPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ControlsRadPane As Global.Telerik.Web.UI.RadPane
    
    '''<summary>
    '''DocumentationFieldset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DocumentationFieldset As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DocumentationTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DocumentationTable As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''NoNotesCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoNotesCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ReferralLetterTD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReferralLetterTD As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''ReferralLetterCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReferralLetterCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''WHOChecklistLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WHOChecklistLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''WHOChecklistRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WHOChecklistRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''CreateProcRadNotification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateProcRadNotification As Global.Telerik.Web.UI.RadNotification
    
    '''<summary>
    '''ValidationSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''RadTabStrip1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTabStrip1 As Global.Telerik.Web.UI.RadTabStrip
    
    '''<summary>
    '''RadMultiPage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultiPage1 As Global.Telerik.Web.UI.RadMultiPage
    
    '''<summary>
    '''RadPageView0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView0 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''ManagementTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManagementTable As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''ManagementNoneCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManagementNoneCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''PulseOximetryCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PulseOximetryCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''OxygenationCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OxygenationCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''OxygenationMethodTD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OxygenationMethodTD As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''OxygenationMethodRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OxygenationMethodRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''OxygenationFlowRateTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OxygenationFlowRateTextBox As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''IVAccessCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IVAccessCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ContinuousECGCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContinuousECGCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''IVAntibioticsCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IVAntibioticsCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ManagementOtherCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManagementOtherCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ManagementOtherTD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManagementOtherTD As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''ManagementOtherTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManagementOtherTextBox As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''BPCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BPCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''BPDetailsDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BPDetailsDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''BPSysTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BPSysTextBox As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''BPDiaTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BPDiaTextBox As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''DefaultRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DefaultRadButton As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''RadPageView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView1 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''PatientSedationTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientSedationTable As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''Fieldset1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fieldset1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PatSedationRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatSedationRadioButton As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''PatSedationAsleepResponseStateComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatSedationAsleepResponseStateComboBox As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''SedationOptionsRequiredFieldValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SedationOptionsRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''Fieldset2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fieldset2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PatDiscomfortEndoRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatDiscomfortEndoRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''PatDiscomfortNurseRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatDiscomfortNurseRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''PatDiscomfortRequiredFieldValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatDiscomfortRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''RadPageView3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView3 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''AdvEventsTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AdvEventsTable As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''chkNoAdverseEvents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNoAdverseEvents As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkConsentSignedInRoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkConsentSignedInRoom As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkUnplannedAdmission control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUnplannedAdmission As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkO2Desaturation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkO2Desaturation As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkWithdrawalOfConsent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWithdrawalOfConsent As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkUnsupervisedTrainee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUnsupervisedTrainee As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkVentilation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVentilation As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''RadPageView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView2 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''ComplicationsTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComplicationsTable As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''ComplicationsNoneCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComplicationsNoneCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''PoorlyToleratedCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PoorlyToleratedCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''DamageToScopeCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DamageToScopeCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''DamageToScopeTypeTD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DamageToScopeTypeTD As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''MechanicalCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MechanicalCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''PatientInitiatedCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientInitiatedCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''HypoxiaCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HypoxiaCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''PatientDiscomfortCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientDiscomfortCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''GastricContentsAspirationCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GastricContentsAspirationCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''RespiratoryDepressionCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RespiratoryDepressionCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''PatientDistressCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientDistressCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ShockHypotensionCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShockHypotensionCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''RespiratoryArrestCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RespiratoryArrestCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''InjuryToMouthCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InjuryToMouthCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''HaemorrhageCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HaemorrhageCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CardiacArrestCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CardiacArrestCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''DifficultIntubationCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DifficultIntubationCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''FailedIntubationCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FailedIntubationCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''SignificantHaemorrhageCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SignificantHaemorrhageCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CardiacArrythmiaCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CardiacArrythmiaCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''DeathCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeathCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''TechnicalFailureTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TechnicalFailureTextBox As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''FailureComplicationsDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FailureComplicationsDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chkAllergyToContrast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllergyToContrast As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkContrast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkContrast As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkArcinarisation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkArcinarisation As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkFailedERCP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFailedERCP As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkFailedCannulation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFailedCannulation As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkFailedStentInsertion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFailedStentInsertion As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkPancreatitis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPancreatitis As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''PerforationCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PerforationCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''PerforationTextBoxDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PerforationTextBoxDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PerforationTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PerforationTextBox As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''ComplicationsOtherCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComplicationsOtherCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ComplicationsOtherTextDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComplicationsOtherTextDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ComplicationsOtherTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComplicationsOtherTextBox As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadPageView4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView4 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''ComplicationsBronchoscopyTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComplicationsBronchoscopyTable As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''ComplicationsBronchoscopyNoneCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComplicationsBronchoscopyNoneCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''BleedingCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BleedingCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''BleedingSeverityComboBoxDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BleedingSeverityComboBoxDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''BleedingSeverityComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BleedingSeverityComboBox As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''GuidelinesButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GuidelinesButton As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''BleedingActionTakenTR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BleedingActionTakenTR As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''ActionTakenFieldset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActionTakenFieldset As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''BleedingColdSalineUsedCheckbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BleedingColdSalineUsedCheckbox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''BleedingAdrenalineUsedCheckbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BleedingAdrenalineUsedCheckbox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''BleedingAdrenalineAmountNumericTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BleedingAdrenalineAmountNumericTextBox As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''BleedingBlockingDeviceUsedCheckbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BleedingBlockingDeviceUsedCheckbox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''PneumothoraxCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PneumothoraxCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''PneumothoraxCheckBoxDetailsDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PneumothoraxCheckBoxDetailsDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PneumothoraxAspirChestDrainCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PneumothoraxAspirChestDrainCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CardiacArrythmiaBronchoscopyCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CardiacArrythmiaBronchoscopyCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''DeathBronchoscopyCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeathBronchoscopyCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''HospitalisationCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HospitalisationCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''AdmissionToIcuCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AdmissionToIcuCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MyocardInfarctionCheckbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MyocardInfarctionCheckbox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''OversedationCheckbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OversedationCheckbox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ComplicationsBronchoscopyOtherCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComplicationsBronchoscopyOtherCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ComplicationsBronchoscopyOtherTextDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComplicationsBronchoscopyOtherTextDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ComplicationsBronchoscopyOtherTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComplicationsBronchoscopyOtherTextBox As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''AbandonedOtherCheckbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AbandonedOtherCheckbox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''AbandonedOtherTextDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AbandonedOtherTextDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''AbandonedOtherTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AbandonedOtherTextBox As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''ButtonsRadPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonsRadPane As Global.Telerik.Web.UI.RadPane
    
    '''<summary>
    '''SaveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveButton As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''CancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButton As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''SaveOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveOnly As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''RadAjaxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As UnisoftERS.ProcedureMaster
        Get
            Return CType(MyBase.Master,UnisoftERS.ProcedureMaster)
        End Get
    End Property
End Class
