'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FITResult

    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''RadNotification1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNotification1 As Global.Telerik.Web.UI.RadNotification

    '''<summary>
    '''FitResultKnownRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FitResultKnownRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''FITValueRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FITValueRadTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FITInfoImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FITInfoImage As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''FITFormatToolTip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FITFormatToolTip As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''FITNotKnownRadComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FITNotKnownRadComboBox As Global.Telerik.Web.UI.RadComboBox
End Class
