'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Indications

    '''<summary>
    '''RadNotification1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNotification1 As Global.Telerik.Web.UI.RadNotification

    '''<summary>
    '''RepeatProcedureDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RepeatProcedureDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RepeatRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RepeatRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RepeatUnknownDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RepeatUnknownDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RepeatNotKnownRadComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RepeatNotKnownRadComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RepeatTextDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RepeatTextDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RepeatTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RepeatTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rptSurveillanceDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSurveillanceDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptSurveillance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSurveillance As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptSectionsDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSectionsDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptSections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSections As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptSubIndicationsDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSubIndicationsDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptSubIndications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSubIndications As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptSubIndicationsAdditionalInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSubIndicationsAdditionalInfo As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptSectionsPlannedDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSectionsPlannedDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptSectionsPlanned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSectionsPlanned As Global.System.Web.UI.WebControls.Repeater
End Class
