'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReferralData

    '''<summary>
    '''RadNotification1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNotification1 As Global.Telerik.Web.UI.RadNotification

    '''<summary>
    '''DateBronchRequestedDatePicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateBronchRequestedDatePicker As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''DateOfReferall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateOfReferall As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''DateOfReferralDatePicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateOfReferralDatePicker As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''blankRowAfterReferal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents blankRowAfterReferal As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''LCaSuspectedBySpecialistCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LCaSuspectedBySpecialistCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CTScanAvailableCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTScanAvailableCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''DateOfScanDatePicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateOfScanDatePicker As Global.Telerik.Web.UI.RadDatePicker
End Class
