'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Products_Gastro_Abnormalities_Colon_Mucosa

    '''<summary>
    '''RadStyleSheetManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadStyleSheetManager1 As Global.Telerik.Web.UI.RadStyleSheetManager

    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''MucosaRadScriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MucosaRadScriptManager As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>
    '''RadFormDecorator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadFormDecorator1 As Global.Telerik.Web.UI.RadFormDecorator

    '''<summary>
    '''RadNotification1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNotification1 As Global.Telerik.Web.UI.RadNotification

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''MainPageRadSplitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainPageRadSplitter As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''ControlsRadPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ControlsRadPane As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''rgAbnormalities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgAbnormalities As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''NoneCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoneCheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Atrophic_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Atrophic_CheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Atrophic_Distribution_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Atrophic_Distribution_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''Atrophic_Severity_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Atrophic_Severity_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''Congested_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Congested_CheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Congested_Distribution_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Congested_Distribution_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''Congested_Severity_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Congested_Severity_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''Erythematous_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Erythematous_CheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Erythematous_Distribution_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Erythematous_Distribution_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''Erythematous_Severity_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Erythematous_Severity_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''Granular_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Granular_CheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Granular_Distribution_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Granular_Distribution_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''Granular_Severity_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Granular_Severity_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''Mucopurulent_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Mucopurulent_CheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Mucopurulent_Distribution_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Mucopurulent_Distribution_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''Mucopurulent_Severity_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Mucopurulent_Severity_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''Pigmented_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pigmented_CheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Pigmented_Distribution_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pigmented_Distribution_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''Pigmented_Severity_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pigmented_Severity_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RedundantRectalRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RedundantRectalRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''RedundantRectal_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RedundantRectal_CheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Ulcerative_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ulcerative_CheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''SmallUlcers_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SmallUlcers_CheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''SmallUlcers_Type_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SmallUlcers_Type_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''LargeUlcers_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LargeUlcers_CheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''LargeUlcers_Type_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LargeUlcers_Type_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''PleomorphicUlcers_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PleomorphicUlcers_CheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''PleomorphicUlcers_Type_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PleomorphicUlcers_Type_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''SerpiginousUlcers_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SerpiginousUlcers_CheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''SerpiginousUlcers_Type_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SerpiginousUlcers_Type_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''AphthousUlcers_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AphthousUlcers_CheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''AphthousUlcers_Type_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AphthousUlcers_Type_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''Cobblestone_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cobblestone_CheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Cobblestone_Distribution_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cobblestone_Distribution_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''Confluent_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Confluent_CheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''DeepUlceration_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeepUlceration_CheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''SolitaryUlcer_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SolitaryUlcer_CheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''DiameterNumericTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiameterNumericTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''Colitis_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Colitis_CheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Ileitis_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ileitis_CheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Proctitis_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Proctitis_CheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''colitisdiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents colitisdiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''InflammatoryRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InflammatoryRadioButtonList As Global.Telerik.Web.UI.RadRadioButtonList

    '''<summary>
    '''raddiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents raddiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ExtentGradingLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtentGradingLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ExtentDropdownlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtentDropdownlist As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ulcerativecolitisdiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ulcerativecolitisdiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MayoScore_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MayoScore_CheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''UCEISScore_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCEISScore_CheckBox As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''mayoscorediv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mayoscorediv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MayoScoreDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MayoScoreDropDownList As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''uceiscorediv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uceiscorediv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptUCEISScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptUCEISScore As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''diverticulosisscorediv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents diverticulosisscorediv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ucDICAScores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucDICAScores As Global.UnisoftERS.DICAScoring

    '''<summary>
    '''chronsdiseasescorediv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chronsdiseasescorediv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ChronsDiseaseScoreLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChronsDiseaseScoreLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SESDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SESDropDownList As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cdeisscorediv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cdeisscorediv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ChronsCDEISScoreLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChronsCDEISScoreLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ChronsCDEISScoreRadNumericTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChronsCDEISScoreRadNumericTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''rutgeertsscorediv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rutgeertsscorediv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RutgeertsScoreLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RutgeertsScoreLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RutgeertsScoreRadComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RutgeertsScoreRadComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ButtonsRadPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonsRadPane As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''SaveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''CancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButton As Global.Telerik.Web.UI.RadButton
End Class
