'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PolypDetails
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock
    
    '''<summary>
    '''RadScriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptManager As Global.Telerik.Web.UI.RadScriptManager
    
    '''<summary>
    '''RadFormDecorator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadFormDecorator As Global.Telerik.Web.UI.RadFormDecorator
    
    '''<summary>
    '''RadNotification1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNotification1 As Global.Telerik.Web.UI.RadNotification
    
    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager
    
    '''<summary>
    '''MainPageRadSplitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainPageRadSplitter As Global.Telerik.Web.UI.RadSplitter
    
    '''<summary>
    '''ControlsRadPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ControlsRadPane As Global.Telerik.Web.UI.RadPane
    
    '''<summary>
    '''PolypDetailsRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PolypDetailsRepeater As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''ButtonsRadPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonsRadPane As Global.Telerik.Web.UI.RadPane
    
    '''<summary>
    '''SaveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveButton As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''CancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButton As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''RadMan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMan As Global.Telerik.Web.UI.RadWindowManager
    
    '''<summary>
    '''SessileParisClassificationPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessileParisClassificationPopup As Global.Telerik.Web.UI.RadWindow
    
    '''<summary>
    '''SessileLSRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessileLSRadioButton As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''testImg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents testImg As Global.Telerik.Web.UI.RadBinaryImage
    
    '''<summary>
    '''SessileLLARadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessileLLARadioButton As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''imgLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgLogo As Global.Telerik.Web.UI.RadBinaryImage
    
    '''<summary>
    '''SessileLLALLCRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessileLLALLCRadioButton As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadBinaryImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadBinaryImage1 As Global.Telerik.Web.UI.RadBinaryImage
    
    '''<summary>
    '''SessileLLBRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessileLLBRadioButton As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadBinaryImage2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadBinaryImage2 As Global.Telerik.Web.UI.RadBinaryImage
    
    '''<summary>
    '''SessileLLCRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessileLLCRadioButton As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadBinaryImage3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadBinaryImage3 As Global.Telerik.Web.UI.RadBinaryImage
    
    '''<summary>
    '''SessileLLCLLARadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessileLLCLLARadioButton As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadBinaryImage4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadBinaryImage4 As Global.Telerik.Web.UI.RadBinaryImage
    
    '''<summary>
    '''SessileParisClassificationRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessileParisClassificationRadButton As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''RadButton2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButton2 As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''PedunculatedParisClassificationPopUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PedunculatedParisClassificationPopUp As Global.Telerik.Web.UI.RadWindow
    
    '''<summary>
    '''ProtrudedRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProtrudedRadioButton As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadBinaryImage11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadBinaryImage11 As Global.Telerik.Web.UI.RadBinaryImage
    
    '''<summary>
    '''PedunculatedRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PedunculatedRadioButton As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadBinaryImage12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadBinaryImage12 As Global.Telerik.Web.UI.RadBinaryImage
    
    '''<summary>
    '''PedunculatedParisClassificationRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PedunculatedParisClassificationRadButton As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''RadButton4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButton4 As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''SessilePitPatternsPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessilePitPatternsPopup As Global.Telerik.Web.UI.RadWindow
    
    '''<summary>
    '''SessileNormalRoundPitsRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessileNormalRoundPitsRadioButton As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''SessileRadBinaryImage5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessileRadBinaryImage5 As Global.Telerik.Web.UI.RadBinaryImage
    
    '''<summary>
    '''SessileStellarRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessileStellarRadioButton As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadBinaryImage6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadBinaryImage6 As Global.Telerik.Web.UI.RadBinaryImage
    
    '''<summary>
    '''SessileTubularRoundPitsRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessileTubularRoundPitsRadioButton As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadBinaryImage7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadBinaryImage7 As Global.Telerik.Web.UI.RadBinaryImage
    
    '''<summary>
    '''SessileTubularRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessileTubularRadioButton As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadBinaryImage8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadBinaryImage8 As Global.Telerik.Web.UI.RadBinaryImage
    
    '''<summary>
    '''SessileSulcusRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessileSulcusRadioButton As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadBinaryImage9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadBinaryImage9 As Global.Telerik.Web.UI.RadBinaryImage
    
    '''<summary>
    '''SessileLossRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessileLossRadioButton As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadBinaryImage10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadBinaryImage10 As Global.Telerik.Web.UI.RadBinaryImage
    
    '''<summary>
    '''SessilePitPatternsRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessilePitPatternsRadButton As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''RadButton6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButton6 As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''PedunculatedPitPatternsPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PedunculatedPitPatternsPopup As Global.Telerik.Web.UI.RadWindow
    
    '''<summary>
    '''PedunculatedNormalRoundPitsRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PedunculatedNormalRoundPitsRadioButton As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''PedunculatedRadBinaryImage5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PedunculatedRadBinaryImage5 As Global.Telerik.Web.UI.RadBinaryImage
    
    '''<summary>
    '''PedunculatedStellarRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PedunculatedStellarRadioButton As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadBinaryImage5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadBinaryImage5 As Global.Telerik.Web.UI.RadBinaryImage
    
    '''<summary>
    '''PedunculatedTubularRoundPitsRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PedunculatedTubularRoundPitsRadioButton As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadBinaryImage13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadBinaryImage13 As Global.Telerik.Web.UI.RadBinaryImage
    
    '''<summary>
    '''PedunculatedTubularRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PedunculatedTubularRadioButton As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadBinaryImage14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadBinaryImage14 As Global.Telerik.Web.UI.RadBinaryImage
    
    '''<summary>
    '''PedunculatedSulcusRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PedunculatedSulcusRadioButton As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadBinaryImage15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadBinaryImage15 As Global.Telerik.Web.UI.RadBinaryImage
    
    '''<summary>
    '''PedunculatedLossRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PedunculatedLossRadioButton As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadBinaryImage16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadBinaryImage16 As Global.Telerik.Web.UI.RadBinaryImage
    
    '''<summary>
    '''PedunculatedPitPatternsRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PedunculatedPitPatternsRadButton As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''RadButton8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButton8 As Global.Telerik.Web.UI.RadButton
End Class
