'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FreeSlotDefaults
    
    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock
    
    '''<summary>
    '''RadFormDecorator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadFormDecorator1 As Global.Telerik.Web.UI.RadFormDecorator
    
    '''<summary>
    '''RadNotification1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNotification1 As Global.Telerik.Web.UI.RadNotification
    
    '''<summary>
    '''RadAjaxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel
    
    '''<summary>
    '''HeadingLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeadingLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''HospitalsComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HospitalsComboBox As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''otherDataFieldset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents otherDataFieldset As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Panel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel3 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DefaultSlotsTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DefaultSlotsTable As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''MondayCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MondayCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MondayMorningCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MondayMorningCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MondayAfternoonCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MondayAfternoonCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MondayEveningCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MondayEveningCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''TuesdayCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TuesdayCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''TuesdayMorningCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TuesdayMorningCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''TuesdayAfternoonCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TuesdayAfternoonCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''TuesdayEveningCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TuesdayEveningCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''WednesdayCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WednesdayCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''WednesdayMorningCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WednesdayMorningCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''WednesdayAfternoonCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WednesdayAfternoonCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''WednesdayEveningCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WednesdayEveningCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ThursdayCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThursdayCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ThursdayMorningCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThursdayMorningCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ThursdayAfternoonCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThursdayAfternoonCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ThursdayEveningCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThursdayEveningCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''FridayCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FridayCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''FridayMorningCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FridayMorningCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''FridayAfternoonCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FridayAfternoonCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''FridayEveningCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FridayEveningCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''SaturdayCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaturdayCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''SaturdayMorningCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaturdayMorningCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''SaturdayAfternoonCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaturdayAfternoonCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''SaturdayEveningCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaturdayEveningCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''SundayCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SundayCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''SundayMorningCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SundayMorningCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''SundayAfternoonCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SundayAfternoonCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''SundayEveningCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SundayEveningCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''SaveRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveRadButton As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''CancelRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelRadButton As Global.Telerik.Web.UI.RadButton
End Class
