'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ERS_PostOperativeComplications
    Public Property Id As Integer
    Public Property ProcedureId As Integer
    Public Property Aspiration As Boolean
    Public Property Arrythmia As Boolean
    Public Property OesophagealPerforation As Boolean
    Public Property OesophagealPerforationSeverity As Nullable(Of Byte)
    Public Property GastricPerforation As Boolean
    Public Property GastricPerforationSeverity As Nullable(Of Byte)
    Public Property BleedingFollowingPolypectomy As Boolean
    Public Property BleedingFollowingPolypectomySeverity As Nullable(Of Byte)
    Public Property MajorBleedingFollowingInjection As Boolean
    Public Property MajorBleedingFollowingInjectionSeverity As Nullable(Of Byte)
    Public Property MajorUlcerationFollowingInjection As Boolean
    Public Property MajorUlcerationFollowingInjectionSeverity As Nullable(Of Byte)
    Public Property Pancreatits As Boolean
    Public Property PancreatitsSeverity As Nullable(Of Byte)
    Public Property AscendingCholangitis As Boolean
    Public Property AscendingCholangitisSeverity As Nullable(Of Byte)
    Public Property Perforation As Boolean
    Public Property PerforationSeverity As Nullable(Of Byte)
    Public Property Haemorrhage As Boolean
    Public Property HaemorrhageSeverity As Nullable(Of Byte)
    Public Property Haemostasis As Boolean
    Public Property HaemostasisSeverity As Nullable(Of Byte)
    Public Property OtherFocal As String
    Public Property Resolution As Nullable(Of Byte)
    Public Property DateOfDeath As Nullable(Of Date)
    Public Property Readmission As Boolean
    Public Property ReadmissionDate As Nullable(Of Date)
    Public Property ReadmissionReason As String
    Public Property RecordedBy As Integer
    Public Property RecordedDate As Date
    Public Property OtherComments As String
    Public Property WhoUpdatedId As Nullable(Of Integer)
    Public Property WhoCreatedId As Nullable(Of Integer)
    Public Property WhenCreated As Nullable(Of Date)
    Public Property WhenUpdated As Nullable(Of Date)
    Public Property InfectionFollowingPEG As Boolean
    Public Property AntibioticsForInfectionFollowingPEG As Boolean
    Public Property BleedingFollowingPEG As Boolean
    Public Property TransfusionForBleedingFollowingPEG As Boolean
    Public Property PeritonitisFollowingPEG As Boolean
    Public Property ScopeCreatedDate As Nullable(Of Date)
    Public Property ScopeDamaged As Nullable(Of Boolean)
    Public Property ScopeDiscovered As Nullable(Of Byte)
    Public Property ScopeDiscoveredOther As String

    Public Overridable Property ERS_Procedures As ERS_Procedures

End Class
