'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ERS_SCH_GenderList
    Public Property GenderListId As Long
    Public Property DiaryId As Integer
    Public Property ListDate As Date
    Public Property Male As Boolean
    Public Property Female As Boolean
    Public Property WhoUpdatedId As Nullable(Of Integer)
    Public Property WhoCreatedId As Nullable(Of Integer)
    Public Property WhenCreated As Nullable(Of Date)
    Public Property WhenUpdated As Nullable(Of Date)

    Public Overridable Property ERS_SCH_DiaryPages As ERS_SCH_DiaryPages

End Class
