'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ERS_Procedures
    Public Property ProcedureId As Integer
    Public Property ProcedureType As Integer
    Public Property CreatedBy As Nullable(Of Integer)
    Public Property CreatedOn As Date
    Public Property ModifiedOn As Date
    Public Property PatientId As Integer
    Public Property PatientType As Nullable(Of Integer)
    Public Property PatientStatus As Nullable(Of Integer)
    Public Property Ward As Nullable(Of Integer)
    Public Property CategoryListId As Nullable(Of Integer)
    Public Property OnWaitingList As Nullable(Of Boolean)
    Public Property OpenAccessProc As Nullable(Of Byte)
    Public Property EmergencyProcType As Nullable(Of Byte)
    Public Property OperatingHospitalID As Integer
    Public Property ReferralHospitalNo As Nullable(Of Integer)
    Public Property ReferralConsultantNo As Nullable(Of Integer)
    Public Property GPReferralFlag As Nullable(Of Short)
    Public Property DiagramNumber As Integer
    Public Property ListType As Nullable(Of Byte)
    Public Property ListConsultant As Nullable(Of Integer)
    Public Property ConsultantPresent As Nullable(Of Boolean)
    Public Property Endoscopist1 As Nullable(Of Integer)
    Public Property Endo1Role As Nullable(Of Byte)
    Public Property Endoscopist2 As Nullable(Of Integer)
    Public Property Endo2Role As Nullable(Of Byte)
    Public Property Assistant As Nullable(Of Integer)
    Public Property Nurse1 As Nullable(Of Integer)
    Public Property Nurse2 As Nullable(Of Integer)
    Public Property Nurse3 As Nullable(Of Integer)
    Public Property Nurse4 As Nullable(Of Integer)
    Public Property Instrument1 As Nullable(Of Integer)
    Public Property Instrument2 As Nullable(Of Integer)
    Public Property ResectedColonNo As String
    Public Property IncludeProcNotes As Nullable(Of Boolean)
    Public Property ProcedureNotes As String
    Public Property Video As Nullable(Of Boolean)
    Public Property VideoNotes As String
    Public Property GPReportText As String
    Public Property TextEdited As Nullable(Of Boolean)
    Public Property DiagramIncluded As Nullable(Of Boolean)
    Public Property EndoscribeComments As String
    Public Property EndoscribePremedication As String
    Public Property MucosalJunctionAt As Nullable(Of Decimal)
    Public Property NewCardia As Nullable(Of Short)
    Public Property AbnoText As String
    Public Property PancreasDivisum As Nullable(Of Short)
    Public Property BiliaryManometry As Nullable(Of Short)
    Public Property PancreaticManometry As Nullable(Of Short)
    Public Property FirstERCP As Nullable(Of Boolean)
    Public Property ExportedToEPR As String
    Public Property ForcepType As Nullable(Of Short)
    Public Property ForcepSerialNo As String
    Public Property AccountNo As String
    Public Property DNA As Nullable(Of Short)
    Public Property DNACombined As Nullable(Of Boolean)
    Public Property DNACreatedViaRC As Nullable(Of Boolean)
    Public Property ExportFileName As String
    Public Property ExportProducedOn As Nullable(Of Date)
    Public Property ReferralConsultantSpeciality As Nullable(Of Short)
    Public Property PatientConsent As Nullable(Of Byte)
    Public Property SurgicalSafetyCheckListCompleted As Nullable(Of Boolean)
    Public Property GPCode As String
    Public Property GPPracticeCode As String
    Public Property NEDEnabled As Nullable(Of Boolean)
    Public Property NEDExported As Nullable(Of Boolean)
    Public Property NEDProcedureId As String
    Public Property ScopeGuide As Nullable(Of Boolean)
    Public Property FormerProcedureId As Nullable(Of Integer)
    Public Property ProcedureCompleted As Nullable(Of Byte)
    Public Property IsDirty As Nullable(Of Boolean)
    Public Property IsActive As Boolean
    Public Property BreathTestResult As Nullable(Of Byte)
    Public Property ImagePortId As Nullable(Of Integer)
    Public Property Transnasal As Nullable(Of Boolean)
    Public Property ReportUpdated As Nullable(Of Boolean)
    Public Property WhoUpdatedId As Nullable(Of Integer)
    Public Property WhoCreatedId As Nullable(Of Integer)
    Public Property WhenCreated As Nullable(Of Date)
    Public Property WhenUpdated As Nullable(Of Date)
    Public Property EUSSuccessful As Nullable(Of Boolean)
    Public Property Points As Nullable(Of Decimal)
    Public Property ChecklistComplete As Nullable(Of Boolean)
    Public Property ReferrerType As Nullable(Of Integer)
    Public Property ReferrerTypeOther As String
    Public Property DistalAttachmentId As Nullable(Of Integer)
    Public Property StartDateTime As Nullable(Of Date)
    Public Property EndDateTime As Nullable(Of Date)
    Public Property ProcedureTime As String
    Public Property ProviderTypeId As Nullable(Of Integer)
    Public Property ProviderOther As String
    Public Property AntiCoagDrugs As Nullable(Of Boolean)
    Public Property PatientNotes As Nullable(Of Boolean)
    Public Property PatientReferralLetter As Nullable(Of Boolean)
    Public Property ImageGenderID As Nullable(Of Integer)
    Public Property PrintedReportFileName As String
    Public Property IsReportEmailed As Nullable(Of Boolean)
    Public Property OrderId As Nullable(Of Integer)
    Public Property LatestReportFileLocation As String
    Public Property ImagesTaken As Nullable(Of Integer)
    Public Property GPReferrer As String
    Public Property LockedBy As String
    Public Property LockedAt As Nullable(Of Date)
    Public Property PotentialSignificantDrugs As Nullable(Of Boolean)
    Public Property PatientConsentType As Nullable(Of Integer)
    Public Property PatientConsentTypeOther As String
    Public Property PreAssessmentId As Nullable(Of Integer)

    Public Overridable Property ERS_ColonExtentOfIntubation As ICollection(Of ERS_ColonExtentOfIntubation) = New HashSet(Of ERS_ColonExtentOfIntubation)
    Public Overridable Property ERS_PatientJourney As ICollection(Of ERS_PatientJourney) = New HashSet(Of ERS_PatientJourney)
    Public Overridable Property ERS_Photos As ICollection(Of ERS_Photos) = New HashSet(Of ERS_Photos)
    Public Overridable Property ERS_PostOperativeComplications As ICollection(Of ERS_PostOperativeComplications) = New HashSet(Of ERS_PostOperativeComplications)
    Public Overridable Property ERS_Users As ERS_Users
    Public Overridable Property ERS_Users1 As ERS_Users
    Public Overridable Property ERS_Users2 As ERS_Users
    Public Overridable Property ERS_Users3 As ERS_Users
    Public Overridable Property ERS_Users4 As ERS_Users
    Public Overridable Property ERS_Users5 As ERS_Users
    Public Overridable Property ERS_Users6 As ERS_Users
    Public Overridable Property ERS_Visualisation As ICollection(Of ERS_Visualisation) = New HashSet(Of ERS_Visualisation)
    Public Overridable Property ERS_RecordCount As ICollection(Of ERS_RecordCount) = New HashSet(Of ERS_RecordCount)
    Public Overridable Property ERS_Sites As ICollection(Of ERS_Sites) = New HashSet(Of ERS_Sites)
    Public Overridable Property ERS_UpperGIFollowUp As ICollection(Of ERS_UpperGIFollowUp) = New HashSet(Of ERS_UpperGIFollowUp)
    Public Overridable Property ERS_UpperGIPathologyResults As ICollection(Of ERS_UpperGIPathologyResults) = New HashSet(Of ERS_UpperGIPathologyResults)
    Public Overridable Property ERS_UpperGIQA As ICollection(Of ERS_UpperGIQA) = New HashSet(Of ERS_UpperGIQA)

End Class
