'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ERS_ProcedureTypes
    Public Property TypeId As Integer
    Public Property ProcedureTypeId As Integer
    Public Property ProcedureType As String
    Public Property ProductTypeId As Integer
    Public Property Suppressed As Boolean
    Public Property ReportHeader As String
    Public Property NedExportRequired As Boolean
    Public Property SchedulerProc As Boolean
    Public Property SchedulerProcName As String
    Public Property SchedulerDiagnostic As Boolean
    Public Property SchedulerTherapeutic As Boolean
    Public Property IsGI As Nullable(Of Boolean)
    Public Property OperatingHospitalId As Nullable(Of Integer)
    Public Property HDCKey As String
    Public Property HL7Code As String
    Public Property WhoUpdatedId As Nullable(Of Integer)
    Public Property WhoCreatedId As Nullable(Of Integer)
    Public Property WhenCreated As Nullable(Of Date)
    Public Property WhenUpdated As Nullable(Of Date)
    Public Property CanExportDocument As Boolean
    Public Property NEDProcedureName As String
    Public Property GenderSpecific As Nullable(Of Boolean)

End Class
