'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ERS_ConsultantProcedureTherapeutics
    Public Property ConsultantProcedureTherapeuticID As Integer
    Public Property ConsultantProcedureID As Integer
    Public Property TherapeuticTypeID As Integer
    Public Property WhoUpdatedId As Nullable(Of Integer)
    Public Property WhoCreatedId As Nullable(Of Integer)
    Public Property WhenCreated As Nullable(Of Date)
    Public Property WhenUpdated As Nullable(Of Date)

    Public Overridable Property ERS_ConsultantProcedureTypes As ERS_ConsultantProcedureTypes
    Public Overridable Property ERS_TherapeuticTypes As ERS_TherapeuticTypes

End Class
