'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ERS_SCH_PointMappings
    Public Property PointsMappingId As Integer
    Public Property Minutes As Integer
    Public Property OperatingHospitalId As Integer
    Public Property ProceduretypeId As Integer
    Public Property Points As Nullable(Of Decimal)
    Public Property WhoUpdatedId As Nullable(Of Integer)
    Public Property WhoCreatedId As Nullable(Of Integer)
    Public Property WhenCreated As Nullable(Of Date)
    Public Property WhenUpdated As Nullable(Of Date)
    Public Property Training As Boolean
    Public Property NonGI As Boolean
    Public Property TherapeuticMinutes As Integer
    Public Property TherapeuticPoints As Nullable(Of Decimal)

    Public Overridable Property ERS_OperatingHospitals As ERS_OperatingHospitals

End Class
