'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ERS_ProceduresReporting
    Public Property ProcedureId As Integer
    Public Property PP_PatAddress As String
    Public Property PP_RefHosp As String
    Public Property PP_CNN As String
    Public Property PP_RepDateAndTime As String
    Public Property PP_RepType As String
    Public Property PP_GP As String
    Public Property PP_PatStatus As String
    Public Property PP_Ward As String
    Public Property PP_RefCons As String
    Public Property PP_Endos As String
    Public Property PP_Instrument As String
    Public Property PP_Premed As String
    Public Property PP_Indic As String
    Public Property PP_MainReportBody As String
    Public Property PP_Diagnoses As String
    Public Property PP_Therapies As String
    Public Property PP_SpecimenTaken As String
    Public Property PP_Rx As String
    Public Property PP_Followup As String
    Public Property PP_Coding As String
    Public Property PP_AdviceAndComments As String
    Public Property PP_EndoComments As String
    Public Property PP_InstForCareHeading As String
    Public Property PP_InstForCare As String
    Public Property PP_InstForCareWithLinks As String
    Public Property TPP_MainReportBody As String
    Public Property TPP_Therapies As String
    Public Property TPP_SpecimenTaken As String
    Public Property PP_Endo1 As String
    Public Property PP_CCRefCons As String
    Public Property PP_CCOther As String
    Public Property PP_CCPatient As String
    Public Property PP_RepHead As String
    Public Property PP_RepSubHead As String
    Public Property PP_OpHosp As String
    Public Property PP_Room_ID As String
    Public Property PP_Priority As String
    Public Property PP_DNA As String
    Public Property PP_NPSAalert As String
    Public Property PP_BBPS As String
    Public Property PP_Site_Legend As String
    Public Property PP_AdviceAndComments_Initial As String
    Public Property PP_Followup_Initial As String
    Public Property PP_Bowel_Prep As String
    Public Property PP_GPName As String
    Public Property PP_GPAddress As String
    Public Property PP_ResectedColon As String
    Public Property PP_Pathology As String
    Public Property Summary As String
    Public Property SummaryWithLinks As String
    Public Property WhoUpdatedId As Nullable(Of Integer)
    Public Property WhoCreatedId As Nullable(Of Integer)
    Public Property WhenCreated As Nullable(Of Date)
    Public Property WhenUpdated As Nullable(Of Date)
    Public Property PP_DNADate As Nullable(Of Date)
    Public Property PP_PatientNotes As String
    Public Property PP_PatientHistory As String
    Public Property PP_Endo2 As String
    Public Property PP_ReBleed As String
    Public Property PP_SubIndications As String
    Public Property PP_InsertionTechnique As String
    Public Property PP_PathwayPlan As String
    Public Property PP_FITResult As String

End Class
