'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DiarySchedule

    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''RadFormDecorator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadFormDecorator1 As Global.Telerik.Web.UI.RadFormDecorator

    '''<summary>
    '''RadNotification1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNotification1 As Global.Telerik.Web.UI.RadNotification

    '''<summary>
    '''RadAjaxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel

    '''<summary>
    '''HeadingLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeadingLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TrustDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrustDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TrustDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrustDropDownList As Global.Telerik.Web.UI.RadDropDownList

    '''<summary>
    '''HospitalDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HospitalDropDownList As Global.Telerik.Web.UI.RadDropDownList

    '''<summary>
    '''RoomsDropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoomsDropdown As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''WeekViewRoomsDropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WeekViewRoomsDropdown As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''SelectRoomButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectRoomButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''BookFromWaitlistRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BookFromWaitlistRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''FindAvailableSlotRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FindAvailableSlotRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''FindExistingBookingRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FindExistingBookingRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''FormDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MonthViewLinkButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MonthViewLinkButton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''DayViewLinkButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DayViewLinkButton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''PreviousDayLinkButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PreviousDayLinkButton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''DiaryDatePicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiaryDatePicker As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''CalendarDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NextDayLinkButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NextDayLinkButton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''TodaysDateLinkButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TodaysDateLinkButton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkZoomOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkZoomOut As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ZoomLevelLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ZoomLevelLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkZoomIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkZoomIn As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SelectedApppointmentId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedApppointmentId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SelectedDateHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedDateHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''imgListLock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgListLock As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ListTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListTypeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GenderTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GenderTypeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RecurrencePatternLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecurrencePatternLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EditListLinkButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditListLinkButton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''AddOverBookedSlotLinkButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddOverBookedSlotLinkButton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''DeleteListLinkButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteListLinkButton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''DiaryIdHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiaryIdHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''OperatingHospitalIdHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OperatingHospitalIdHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ListRulesIdHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListRulesIdHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''RoomIdHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoomIdHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''EndoscopistIdHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndoscopistIdHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''IsRecurringHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IsRecurringHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ListConsultantLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListConsultantLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ListEndoscopistLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListEndoscopistLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ListStartLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListStartLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ListEndLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListEndLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ListPointsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListPointsLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowAmendedBookingsLinkButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowAmendedBookingsLinkButton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''CancelledListDivButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelledListDivButton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ListNotesTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListNotesTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DiaryRadScheduler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiaryRadScheduler As Global.Telerik.Web.UI.RadScheduler

    '''<summary>
    '''SlotContextMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlotContextMenu As Global.Telerik.Web.UI.RadSchedulerContextMenu

    '''<summary>
    '''SchedulerAppointmentContextMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SchedulerAppointmentContextMenu As Global.Telerik.Web.UI.RadSchedulerContextMenu

    '''<summary>
    '''BlockedSlotContextMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BlockedSlotContextMenu As Global.Telerik.Web.UI.RadSchedulerContextMenu

    '''<summary>
    '''SchedulerBookingContextMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SchedulerBookingContextMenu As Global.Telerik.Web.UI.RadSchedulerContextMenu

    '''<summary>
    '''DiaryPageContextMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiaryPageContextMenu As Global.Telerik.Web.UI.RadSchedulerContextMenu

    '''<summary>
    '''LockedDiaryContextMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LockedDiaryContextMenu As Global.Telerik.Web.UI.RadSchedulerContextMenu

    '''<summary>
    '''DiaryOverviewRadScheduler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiaryOverviewRadScheduler As Global.Telerik.Web.UI.RadScheduler

    '''<summary>
    '''OverviewSlotRadSchedulerContextMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OverviewSlotRadSchedulerContextMenu As Global.Telerik.Web.UI.RadSchedulerContextMenu

    '''<summary>
    '''DiaryOverviewRadSchedulerContextMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiaryOverviewRadSchedulerContextMenu As Global.Telerik.Web.UI.RadSchedulerContextMenu

    '''<summary>
    '''AppointmentsDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AppointmentsDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CancelMoveLinkButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelMoveLinkButton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''TemplatesObjectDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TemplatesObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''RoomsDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoomsDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''ConsultantDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConsultantDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''TrustObjectDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrustObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''HospitalObjectDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HospitalObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''HospitalRoomsDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HospitalRoomsDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''DiaryPagesRadWindowManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiaryPagesRadWindowManager As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''PatientBookingRadWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientBookingRadWindow As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''EditListSlotRadWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditListSlotRadWindow As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''ModeHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModeHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SlotStartHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlotStartHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''GIProcedureRBL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GIProcedureRBL As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''SlotComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlotComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ProcedureTypesComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProcedureTypesComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''PointsRadNumericTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PointsRadNumericTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''SlotLengthRadNumericTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlotLengthRadNumericTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''SlotQtyRadNumericTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlotQtyRadNumericTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''btnSaveAndApply control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveAndApply As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''SlotStatusObjectDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlotStatusObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''GuidelineObjectDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GuidelineObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''DiaryAppointmentsWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiaryAppointmentsWindow As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''DiaryAppointmentsRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiaryAppointmentsRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''SaveRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''CancelRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''OkRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OkRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ConfirmMoveDestinationAndTimeRadWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmMoveDestinationAndTimeRadWindow As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''MoveNotificationTextLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MoveNotificationTextLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''YesMoveRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YesMoveRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''NoMoveRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoMoveRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''PatientDeleteBookingConfirmationWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientDeleteBookingConfirmationWindow As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''PatientAppointmentIDHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientAppointmentIDHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''YesCancelBookingRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YesCancelBookingRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''NoCancelBookingRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoCancelBookingRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''CancelledActionRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelledActionRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''CancellationReasonRadComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancellationReasonRadComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''CancellationReasonsObjectDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancellationReasonsObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''chkReturnToWaitlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkReturnToWaitlist As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ConfirmDeleteBookingRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmDeleteBookingRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''CancelConfirmDeleteBookingRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelConfirmDeleteBookingRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ListCancellConfirmationWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListCancellConfirmationWindow As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''RadButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButton1 As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadButton2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButton2 As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ListCancellConfirmationComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListCancellConfirmationComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ListCancellationReasonsObjectDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListCancellationReasonsObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''ListTextArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListTextArea As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ConfirmScheduleCancelRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmScheduleCancelRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''CancelScheduleCancelRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelScheduleCancelRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ExternalRadWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExternalRadWindow As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''TemplateRadWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TemplateRadWindow As Global.Telerik.Web.UI.RadWindow
End Class
