'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PatientBooking

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''RadAjaxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel

    '''<summary>
    '''RadFormDecorator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadFormDecorator1 As Global.Telerik.Web.UI.RadFormDecorator

    '''<summary>
    '''SelectedDiaryIdHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedDiaryIdHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SelectedSlotDateHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedSlotDateHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SelectedRoomIdHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedRoomIdHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''PatientSearchDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientSearchDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PatientSearchBookingWindowRadNotification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientSearchBookingWindowRadNotification As Global.Telerik.Web.UI.RadNotification

    '''<summary>
    '''PatientSearchCNNTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientSearchCNNTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CountryOfOriginHealthServiceNoRadTextBoxSearchRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CountryOfOriginHealthServiceNoRadTextBoxSearchRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''HealthServiceNameIdTd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HealthServiceNameIdTd As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''PatientSearchHealthServiceNoRadTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientSearchHealthServiceNoRadTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PatientSearchSurnameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientSearchSurnameTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PatientSearchForenameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientSearchForenameTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SearchPatientButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchPatientButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''CancelSearchPatientButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelSearchPatientButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadTabStrip1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTabStrip1 As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''RadPatients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPatients As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''searchResultsRadPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchResultsRadPage As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''lblWelcomeMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWelcomeMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PatientNotFoundLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientNotFoundLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PatientSearchResultsRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientSearchResultsRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''BookingDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BookingDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CanNotCreateAppointmentRadNotification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CanNotCreateAppointmentRadNotification As Global.Telerik.Web.UI.RadNotification

    '''<summary>
    '''ConfirmContinueBookingRadNotification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmContinueBookingRadNotification As Global.Telerik.Web.UI.RadNotification

    '''<summary>
    '''ConfirmContinueBookingMessageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmContinueBookingMessageLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''YesContinueBookingRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YesContinueBookingRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''CancelBookingRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelBookingRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''BookingErrorRadNotification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BookingErrorRadNotification As Global.Telerik.Web.UI.RadNotification

    '''<summary>
    '''BookingWindowRadNotification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BookingWindowRadNotification As Global.Telerik.Web.UI.RadNotification

    '''<summary>
    '''BookingDetailsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BookingDetailsLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NavigateToBookingRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NavigateToBookingRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''NavigateToTodayRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NavigateToTodayRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''lblRemainingReservedTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRemainingReservedTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ProcedureTypesValidationLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProcedureTypesValidationLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GIProceduresDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GIProceduresDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SlotRunningTotalHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlotRunningTotalHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''PatientBookingProceduresRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientBookingProceduresRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''NonGIProceduresDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NonGIProceduresDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''NonGIProcedureLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NonGIProcedureLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ProcedureTypeHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProcedureTypeHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''NonGIProcedureTypeRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NonGIProcedureTypeRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''BookingLengthRadNumericTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BookingLengthRadNumericTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''BookingPointsRadNumericTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BookingPointsRadNumericTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''PatientBookingStatusValidationLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientBookingStatusValidationLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PatientBookedStatusRadioButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientBookedStatusRadioButtons As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''PatientSlotStatusValidationLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientSlotStatusValidationLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PatientBookingSlotStatusRadioButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientBookingSlotStatusRadioButtons As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''PatientIDHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientIDHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''PatientNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PatientDOBLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientDOBLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PatientCaseNoteLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientCaseNoteLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CountryOfOriginHealthServiceNoBookingRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CountryOfOriginHealthServiceNoBookingRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''HealthServiceNameIdBookingTd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HealthServiceNameIdBookingTd As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''PatientNHSNoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientNHSNoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PatientGenderLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientGenderLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BookingReferralDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BookingReferralDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''FirstOfferDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstOfferDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BookingFirstOfferDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BookingFirstOfferDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''SecondOfferDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SecondOfferDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BookingSecondOfferDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BookingSecondOfferDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''PatientEndoscopistHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientEndoscopistHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''PatientEndoscopistLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientEndoscopistLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PatientListConsultantHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientListConsultantHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''PatientListConsultantLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientListConsultantLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PatientAlertNotesTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientAlertNotesTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''PatientGeneralInfoNotesTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PatientGeneralInfoNotesTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ScheduleDetailsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScheduleDetailsLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CallInTimeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CallInTimeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CallInTimeRadTimePicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CallInTimeRadTimePicker As Global.Telerik.Web.UI.RadTimePicker

    '''<summary>
    '''StartTimeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StartTimeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''StartTimeRadTimePicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StartTimeRadTimePicker As Global.Telerik.Web.UI.RadTimePicker

    '''<summary>
    '''LengthOfSlotLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LengthOfSlotLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BookingSlotLengthRadNumericTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BookingSlotLengthRadNumericTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''TotalSlotPointsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TotalSlotPointsLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BookingSlotPointsRadNumericTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BookingSlotPointsRadNumericTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''RadioButtonLetterPrintList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonLetterPrintList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''NotTemplateFoundLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NotTemplateFoundLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SaveBookingRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveBookingRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''CancelSaveBookingRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelSaveBookingRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ValidationNotification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationNotification As Global.Telerik.Web.UI.RadNotification

    '''<summary>
    '''SaveBookingValidationSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveBookingValidationSummary As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''ServerErrorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ServerErrorLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AddNewTitleRadWindowManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddNewTitleRadWindowManager As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''PreviousPatientBookingsWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PreviousPatientBookingsWindow As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''PreviousBookingMessageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PreviousBookingMessageLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContinueBookingRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContinueBookingRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''CancelButtonRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButtonRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''TherapeuticTypesSelectionRadWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TherapeuticTypesSelectionRadWindow As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''LetterPrintEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LetterPrintEdit As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''SlotStatusObjectDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlotStatusObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''NonGIProceduresObjectDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NonGIProceduresObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''ProcedureTypesObjectDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProcedureTypesObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
