'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Products_Gastro_Oesophagitis_OGDOesophagitis

    '''<summary>
    '''RadStyleSheetManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadStyleSheetManager1 As Global.Telerik.Web.UI.RadStyleSheetManager

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''OGDOesophagitisRadScriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OGDOesophagitisRadScriptManager As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>
    '''RadFormDecorator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadFormDecorator1 As Global.Telerik.Web.UI.RadFormDecorator

    '''<summary>
    '''RadNotification1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNotification1 As Global.Telerik.Web.UI.RadNotification

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''MainPageRadSplitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainPageRadSplitter As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''ControlsRadPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ControlsRadPane As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''FormDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rgOesophagitis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgOesophagitis As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''NoneCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoneCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LAClassificationFieldset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LAClassificationFieldset As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LA_RefluxCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LA_RefluxCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LA_ActiveBleedingCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LA_ActiveBleedingCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LA_ShortOesophagusCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LA_ShortOesophagusCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''hfLAClassification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfLAClassification As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Fieldset2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fieldset2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LA_GradeARadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LA_GradeARadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Fieldset3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fieldset3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LA_GradeBRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LA_GradeBRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Fieldset4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fieldset4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LA_GradeCRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LA_GradeCRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Fieldset5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fieldset5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LA_GradeDRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LA_GradeDRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''MSMFieldset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MSMFieldset As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MSM_RefluxCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MSM_RefluxCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''MSM_ActiveBleedingCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MSM_ActiveBleedingCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Grade1CheckBox_ME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grade1CheckBox_ME As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Grade1Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grade1Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Grade2aCheckBox_ME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grade2aCheckBox_ME As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Grade2aLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grade2aLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Grade2bCheckBox_ME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grade2bCheckBox_ME As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Grade2bLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grade2bLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Grade3CheckBox_ME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grade3CheckBox_ME As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Grade3Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grade3Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Grade4CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grade4CheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Grade4Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grade4Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MSM_ShortOesophagusCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MSM_ShortOesophagusCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Grade5CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grade5CheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Grade5Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grade5Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Fieldset1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fieldset1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Caustic_Ingestion_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Caustic_Ingestion_CheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Caustic_Ingestion_Other_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Caustic_Ingestion_Other_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''Suspected_Candida_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Suspected_Candida_CheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Suspected_Candida_Other_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Suspected_Candida_Other_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''Suspected_Herpes_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Suspected_Herpes_CheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Suspected_Herpes_Other_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Suspected_Herpes_Other_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''Corrosive_Burns_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Corrosive_Burns_CheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Corrosive_Burns_Other_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Corrosive_Burns_Other_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''Eosinophilic_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eosinophilic_CheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Eosinophilic_Other_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eosinophilic_Other_ComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''UlcerationTR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UlcerationTR As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Ulceration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ulceration As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''UlcerationMultipleCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UlcerationMultipleCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''UlcerationQtyNumericTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UlcerationQtyNumericTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''UlcerationLengthNumericTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UlcerationLengthNumericTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''UlcerationClotInBase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UlcerationClotInBase As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''UlcerationReflux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UlcerationReflux As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''UlcerationPostSclero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UlcerationPostSclero As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''UlcerationPostBanding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UlcerationPostBanding As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Other_Other_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Other_Other_CheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''OtherTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OtherTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''SaveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''CancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButton As Global.Telerik.Web.UI.RadButton
End Class
