'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Products_Gastro_Abnormalities_ERCP_Duct

    '''<summary>
    '''RadStyleSheetManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadStyleSheetManager1 As Global.Telerik.Web.UI.RadStyleSheetManager

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''DuctRadScriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DuctRadScriptManager As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>
    '''DuctRadFormDecorator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DuctRadFormDecorator As Global.Telerik.Web.UI.RadFormDecorator

    '''<summary>
    '''RadNotification1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNotification1 As Global.Telerik.Web.UI.RadNotification

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''HeadingLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeadingLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MainPageRadSplitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainPageRadSplitter As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''ControlsRadPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ControlsRadPane As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''rgAbnormalities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgAbnormalities As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''NormalCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NormalCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''DilatedCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DilatedCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''DilatedLengthNumericTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DilatedLengthNumericTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''DilatedTypeRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DilatedTypeRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''StrictureCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StrictureCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''StrictureLengthNumericTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StrictureLengthNumericTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''UpstreamDilatationCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpstreamDilatationCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CompleteBlockCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompleteBlockCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SmoothCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SmoothCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''IrregularCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IrregularCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ShoulderedCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShoulderedCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''TortuousCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TortuousCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''StrictureTypeRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StrictureTypeRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''ProbablyCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProbablyCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''StrictureTypeMalignantRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StrictureTypeMalignantRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''StrictureTypeMalignantCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StrictureTypeMalignantCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''CholangiocarcinomaCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CholangiocarcinomaCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ExternalCompressionCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExternalCompressionCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''FistulaCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FistulaCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''FistulaQtyNumericTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FistulaQtyNumericTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''VisceralCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VisceralCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CutaneousCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CutaneousCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CommentsTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CommentsTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''StonesCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StonesCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''StonesMultipleCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StonesMultipleCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''StonesQtyNumericTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StonesQtyNumericTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''StonesSizeNumericTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StonesSizeNumericTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''trCysts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trCysts As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''CystsCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CystsMultipleCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsMultipleCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CystsQtyNumericTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsQtyNumericTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''CystsDiameterNumericTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsDiameterNumericTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''CystsSimpleCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsSimpleCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CystsRegularCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsRegularCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CystsIrregularCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsIrregularCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CystsLoculatedCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsLoculatedCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CystsCholedochalDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsCholedochalDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CystsCholedochalCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsCholedochalCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CystsCommunicatingCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsCommunicatingCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CystsSuspectedRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsSuspectedRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''CystsSuspectedCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsSuspectedCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''CystsSuspectedTypeRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsSuspectedTypeRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''DuctInjuryCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DuctInjuryCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''StentOcclusionCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StentOcclusionCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''GallBladderTumorRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GallBladderTumorRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''GallBladderTumorCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GallBladderTumorCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''DiverticulumRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiverticulumRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''DiverticulumCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiverticulumCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''AnastomicStrictureRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AnastomicStrictureRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''AnastomicStrictureCheckbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AnastomicStrictureCheckbox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''MirizziSyndromeRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MirizziSyndromeRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''MirizziSyndromeCheckbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MirizziSyndromeCheckbox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SclerosingCholangitisRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SclerosingCholangitisRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''SclerosingCholangitisCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SclerosingCholangitisCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CalculousObstructionRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalculousObstructionRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''CalculousObstructionCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalculousObstructionCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''OcclusionRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OcclusionRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''OcclusionCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OcclusionCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''BiliaryLeakRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BiliaryLeakRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''BiliaryLeakCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BiliaryLeakCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''PreviousSurgeryRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PreviousSurgeryRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''PreviousSurgeryCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PreviousSurgeryCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''PancreaticTumourRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PancreaticTumourRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''PancreaticTumourCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PancreaticTumourCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''IPMNRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IPMNRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IPMNCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IPMNCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''MigratedStentRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MigratedStentRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''MigratedStentCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MigratedStentCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''HemobiliaRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HemobiliaRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''HemobiliaCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HemobiliaCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CholangiopathyRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CholangiopathyRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''CholangiopathyCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CholangiopathyCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''MassDistortingAnatomyCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MassDistortingAnatomyCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''MassDistortingAnatomyChildRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MassDistortingAnatomyChildRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''MassTypeRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MassTypeRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''CheckBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''OtherCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OtherCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''OtherTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OtherTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ButtonsRadPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonsRadPane As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''SaveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''CancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButton As Global.Telerik.Web.UI.RadButton
End Class
