'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Products_Gastro_Abnormalities_ERCP_Parenchyma

    '''<summary>
    '''RadStyleSheetManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadStyleSheetManager1 As Global.Telerik.Web.UI.RadStyleSheetManager

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ParenchymaRadScriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ParenchymaRadScriptManager As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>
    '''ParenchymaFormDecorator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ParenchymaFormDecorator As Global.Telerik.Web.UI.RadFormDecorator

    '''<summary>
    '''RadNotification1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNotification1 As Global.Telerik.Web.UI.RadNotification

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''MainPageRadSplitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainPageRadSplitter As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''ControlsRadPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ControlsRadPane As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''rgAbnormalities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgAbnormalities As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''NoneCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoneCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''IrregularDuctulesCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IrregularDuctulesCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''DilatedDuctulesCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DilatedDuctulesCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SmallLakesCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SmallLakesCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''StricturesCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StricturesCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''MassDistortingAnatomyCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MassDistortingAnatomyCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''MassDistortingAnatomyChildRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MassDistortingAnatomyChildRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''MassTypeRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MassTypeRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''ProbablyCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProbablyCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trCysts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trCysts As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''CystsCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CystsMultipleCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsMultipleCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CystsQtyNumericTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsQtyNumericTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''CystsDiameterNumericTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsDiameterNumericTextBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''CystsSimpleCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsSimpleCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CystsRegularCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsRegularCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CystsIrregularCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsIrregularCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CystsLoculatedCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsLoculatedCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CystsCholedochalDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsCholedochalDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CystsCholedochalCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsCholedochalCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CystsCommunicatingCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsCommunicatingCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CystsSuspectedRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsSuspectedRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''CystsSuspectedCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsSuspectedCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''CystsSuspectedTypeRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CystsSuspectedTypeRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''SpideryStretchedDuctulesRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SpideryStretchedDuctulesRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''SpideryStretchedDuctulesCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SpideryStretchedDuctulesCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SpideryDuctulesRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SpideryDuctulesRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''MultipleStricturesRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultipleStricturesRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''MultipleStricturesCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultipleStricturesCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''MultipleStricturesRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultipleStricturesRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''AnnulareCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AnnulareCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''OcclusionCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OcclusionCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''BiliaryLeakCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BiliaryLeakCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''PreviousSurgeryCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PreviousSurgeryCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''PancreatitisRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PancreatitisRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''PancreatitisCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PancreatitisCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''PancreatitisTypeRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PancreatitisTypeRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''OtherCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OtherCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''OtherTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OtherTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ButtonsRadPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonsRadPane As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''SaveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''CancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButton As Global.Telerik.Web.UI.RadButton
End Class
